[package]
name = "fv1-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fv1-asm.workspace = true
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.0", features = ["fancy"] }
